name = "drive-deal-api"
main = "api/index.ts"
compatibility_date = "2024-02-28"

# KV Namespace binding
[[kv_namespaces]]
binding = "SESSIONS"
id = "a825d524c3cd4884b33126f725cd7706"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "drive-deal"
database_id = "e86855c3-006f-4695-90dc-21fc5fa98907"

[vars]
JWT_SECRET = "your-jwt-secret-here"

# Development environment
[env.development]
name = "drive-deal-api-dev"
workers_dev = true

# Production environment
[env.production]
workers_dev = false
route = "api.drive-deal.com/*"
zone_id = "your-zone-id" 